In [2]:
import numpy as np

data = np.array([1, 2, 3, 4, 5, 6, 7])
window_size = 4
weights = np.ones(window_size) / window_size

moving_avg = np.convolve(data, weights, mode='valid') # -> output: [2. 3. 4. 5. 6.]
# moving_avg = np.convolve(data, weights, mode='same') # -> fill the edges with zeros
# moving_avg = np.convolve(data, weights, mode='full') 

print(moving_avg)

[2.5 3.5 4.5 5.5]


In [13]:
a = np.zeros((4, 4, 4))

for d0 in range(4):
    for d2 in range(4):
        a[d0, :3, d2] = np.array([1,2,3]) 
        
a

array([[[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [0., 0., 0., 0.]],

       [[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.],
        [0., 0., 0., 0.]]])

In [14]:
a_reduced = a[:, :3, :]
a_reduced

array([[[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]],

       [[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]],

       [[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]],

       [[1., 1., 1., 1.],
        [2., 2., 2., 2.],
        [3., 3., 3., 3.]]])

In [15]:
int(5/2)

2